const CATEGORIES = {
  featured: { name: "تطبيقات مميزة" },
  social:   { name: "تواصل" },
  tools:    { name: "أدوات" },
};

const APPS = [

 {
  id: "DNS",
  category: "DNS",
  name: "DNS installer",
  version: "2.1.4",
  size: "5MB",
  rating: "4.9",
  developer: "khoindvn",
  updated: "2026-01-26",
  icon: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA6DAGPGXb2orzb4b8_cOOFZu_TVoeoeRg2A&s",
  description: "لازم تنزل هذا الكونفنك علمود تكدر تنزل التطبيقات",
  downloadUrl: "https://github.com/Nyasami/getUDID-JS/releases/download/1.0.0/signed_khoindvn_fullchain.mobileconfig"
},

 {
  id: "uYouTube",
  category: "social",
  name: "YouTube",
  version: "1",
  size: "135MB",
  rating: "7.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/youtube.png",
  description: "يوتيوب بدون اعلانات الاصدار الاكثر استقرار",
  downloadUrl: "https://www.transfernow.net/d/start?utm_source=20260126gAO0zeZj&utm_medium=4IPTWsu1&utm_term=LMC56r "
},
 {
  id: "instagram",
  category: "social",
  name: "instagram ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/instagram.jpg",
  description: "انستاكرام مدموج بأداة ريكرام مفتوحة المميزات بدون اشتراك",
  downloadUrl: " "
},
{
  id: "TikTok",
  category: "social",
  name: "TikTok ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/tiktok.png",
  description: "تيكنوك مفتوحة المميزات بدون اشتراك",
  downloadUrl: " "
},
{
  id: "WhatsApp",
  category: "social",
  name: "WhatsApp ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/watsapp.png",
  description: "لرؤية مميزات التطبيق زورنا على قناتنا في التلكرام",
  downloadUrl: " "
},

{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},
{
  id: "Esign",
  category: "esign",
  name: "Esign ",
  version: "1",
  size: "158.6MB",
  rating: "6.9",
  developer: "Mahmoud Ahmed",
  updated: "2026-01-26",
  icon: "apps icon/esign-ipa.avif",
  description: "تطبيق لتحميل الملفات والتطبيقات من خارج ابل ستةر",
  downloadUrl: " "
},

];